version: '3'
services:
  ds:
    image: datascience:latest
    container_name: ds
    hostname: ds
    build:
      context: .
      dockerfile: ./notebooks/Dockerfile
    env_file:
      - .env
    ports:
      - 8888:8888
    volumes:
      - .:/srv
    restart: unless-stopped
